# Generated by Django 5.1.6 on 2025-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('is_in_school', models.BooleanField(blank=True, null=True)),
                ('is_in_school_authenticated', models.BooleanField(blank=True, null=True)),
                ('current_student_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('college_enter_year', models.IntegerField(blank=True, null=True)),
                ('is_invited_to_school', models.BooleanField(blank=True, null=True)),
                ('school_invitor', models.CharField(blank=True, max_length=255, null=True)),
                ('school_invitation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('location_province', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_certificate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mianji_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('is_real_person_authenticated', models.BooleanField(blank=True, null=True)),
                ('avatar_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_avatar_checked', models.BooleanField(blank=True, null=True)),
                ('is_safe_authenticated', models.BooleanField(blank=True, null=True)),
                ('last_safe_authenticated_time', models.BigIntegerField(blank=True, null=True)),
                ('last_pay_safe_authenticated_time', models.BigIntegerField(blank=True, null=True)),
                ('safe_json', models.CharField(blank=True, max_length=255, null=True)),
                ('is_married', models.BooleanField(blank=True, null=True)),
                ('is_married_authenticated', models.BooleanField(blank=True, null=True)),
                ('last_married_authenticated_time', models.BigIntegerField(blank=True, null=True)),
                ('last_pay_married_authenticated_time', models.BigIntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('hukou_province', models.CharField(blank=True, max_length=255, null=True)),
                ('hukou_city', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown_province', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown_city', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('house_purchased', models.BooleanField(blank=True, null=True)),
                ('house_purchased_city', models.CharField(blank=True, max_length=255, null=True)),
                ('car_purchased', models.BooleanField(blank=True, null=True)),
                ('license_plate_city', models.CharField(blank=True, max_length=255, null=True)),
                ('wealth_level', models.CharField(blank=True, max_length=255, null=True)),
                ('is_wealth_level_authenticated', models.BooleanField(blank=True, null=True)),
                ('extend_authentication', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('tags_like', models.JSONField(blank=True, null=True)),
                ('images_desc_list', models.JSONField(blank=True, null=True)),
                ('characters', models.JSONField(blank=True, null=True)),
                ('psychological_evaluations', models.JSONField(blank=True, null=True)),
                ('valid_mian_ji_s', models.JSONField(blank=True, null=True)),
                ('moments', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
